name: 'build'

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            name: "macos-arm"
            args: '--target aarch64-apple-darwin'
            mobile: ''
            artifacts: src-tauri/target/aarch64-apple-darwin/release/bundle/**/*.dmg

          - platform: 'macos-latest' # for Intel based macs.
            name: "macos-x86_64"
            args: '--target x86_64-apple-darwin'
            mobile: ''
            artifacts: src-tauri/target/x86_64-apple-darwin/release/bundle/**/*.dmg

          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            name: 'linux'
            args: ''
            mobile: ''
            artifacts: |
              src-tauri/target/release/bundle/**/*.deb
              src-tauri/target/release/bundle/**/*.rpm
              src-tauri/target/release/bundle/**/*.AppImage

          - platform: 'windows-latest'
            name: 'windows'
            args: ''
            mobile: ''
            artifacts: src-tauri/target/release/bundle/**/*.exe

          - platform: 'ubuntu-22.04'
            name: 'android'
            args: ''
            mobile: 'android'
            artifacts: src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk

#          - platform: 'macos-latest'
#            name: 'ios'
#            args: ''
#            mobile: 'ios'
#            artifacts: []

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: cache Rust artifacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install Java 21 (android only)
        if: matrix.mobile == 'android'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: setup Android signing
        if: matrix.mobile == 'android'
        run: |
          cd src-tauri/gen/android
          echo 'keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}' > keystore.properties
          echo 'storePassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> keystore.properties
          echo 'keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> keystore.properties
          base64 -d <<< '${{ secrets.ANDROID_KEY_BASE64 }}' > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@390cbe447412ced1303d35abe75287949e43437a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
          mobile: ${{ matrix.mobile }}

      - uses: actions/upload-artifact@v4
        with:
          name: '${{ matrix.name }}-bin'
          path: '${{ github.workspace }}/${{ matrix.artifacts }}'
